[build]
  command = "npm.cmd run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/clinics"
  to = "/.netlify/functions/clinics"
  status = 200

[[redirects]]
  from = "/"
  to = "/clinic/:slug"
  status = 301
  force = true
  query = { clinic = ":slug" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
